name: API testing with Playwright
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Run all tests
      run: npm run test-run
    - uses: actions/checkout@v2
      if: always()
      with:
        repository: txt2021/API_Testing_Playwright
        ref:  report
        path: ./docs   
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: report
        path: playwright-report/
        retention-days: 30
    - name: Push to repository
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_TOKEN }}
      with:
        source-directory: 'playwright-report'
        destination-github-username: 'txt2021'
        destination-repository-name: 'API_Testing_Playwright'
        user-email: txt2021@gmail.com
        target-branch: report




